---

- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: create haproxy.cfg
  template:
    src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - start haproxy
    - enable haproxy

